### ISSUE TITLE
As a <Spier> I have to <enter a keyword> so that <the server can evaluate if anyone guessed the object correctly>.

### ISSUE THREAD

**Issue by athzsc** [sopra-fs23-group-09/SpyWithMyLittleEye_server#12]
/- Before starting the game for the guessers, the user has to enter a keyword.
- The server will use this keyword to evaluate if the guesses of the guessers are correct.
- The spier has to also enter the color of his chosen object. This color will be displayed to the players in the beginning of the round.

- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#32
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#31
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#33
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_server#72
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#31
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#24
