### ISSUE TITLE
As a <Player> I want to <see what the others have guessed wrong> so that <I know which guesses are wrong and what to look for when continuing>.

### ISSUE THREAD

**Issue by athzsc** [sopra-fs23-group-09/SpyWithMyLittleEye_server#13]
- The wrong guesses should be shown on the screen after being evaluated for all players to see.

- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#42
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#43
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#44
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#41
