### ISSUE TITLE
As a <User> I want to <see if someone guessed correctly> so that <the round ends>.

### ISSUE THREAD

**Issue by athzsc** [sopra-fs23-group-09/SpyWithMyLittleEye_server#14]
- The round automatically ends when all users have successfully guessed the object.
- The winner of the round is announced.

- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#29
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#36
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_server#80

**Comment by athzsc** [comment]
We changed our logic: Only if all users guessed correctly or the time is over the round is over.
