### ISSUE TITLE
As a <user> I want to <be able to see my profile page> so that <I can see my information (e.g. personal high score) and edit information>.

### ISSUE THREAD

**Issue by athzsc** [sopra-fs23-group-09/SpyWithMyLittleEye_server#3]
- The user can access their profile page by clicking either on their username in the User Overview Page or by clicking on a button labeled “My Profile”.
- Only logged in users can access profile pages.
- On the user's own page, they can opt to edit their personal information.

- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#3
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#2
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#189
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_server#35
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_server#36
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_server#37
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#84
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#175
