### ISSUE TITLE
As a <user> I want to <see a ranked list of the top 100 of the registered accounts by username and high score> so that <I can compare myself to other players>.

### ISSUE THREAD

**Issue by athzsc** [sopra-fs23-group-09/SpyWithMyLittleEye_server#4]
- The personal high score of the user is displayed next to his username on the user overview.
- After successful login or registration the user overview screen is shown.
- Only logged in users can access the ranked list
- The user overview should show all the usernames and the high scores of all the registered users next to each other.
- The high score is always updated if a higher score is reached in a game than in the games before.
- In the user overview page the user sees an overview of users, ranked by their score. 

- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#12
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#13
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_server#43
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#177
