### ISSUE TITLE
As a <user> I want to <be able to start a game session> so that <I can send the generated code to my friends to be able to play with them>.

### ISSUE THREAD

**Issue by athzsc** [sopra-fs23-group-09/SpyWithMyLittleEye_server#5]
- The user can start a game when clicking on a button “Start game” on the game view.
- The button will generate a code.
- The user that started the game will automatically be in the game.
- The players wait in the lobby until the person who generated the code starts the game by pressing a button.
-  A user can only be in one lobby at a time.

- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#17
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#18
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#19
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_server#88
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#46
