### ISSUE TITLE
As a <User> I want to <join a game session by entering a code> so that <I can enter a lobby room>.

### ISSUE THREAD

**Issue by athzsc** [sopra-fs23-group-09/SpyWithMyLittleEye_server#6]
- The user can enter the code in a given space to enter the game.
- If there is an error (e.g. code is not correct) there will be an error message shown.
- After entering the correct code, the user enters a lobby and becomes part of the game.

- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#20
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_server#48
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#19
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#67
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#85
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#66
