### ISSUE TITLE
As a <User> I want <to be able to play the game with 2-10 people>  so that <we can play together>.

### ISSUE THREAD

**Issue by athzsc** [sopra-fs23-group-09/SpyWithMyLittleEye_server#7]
- The game can only start when at least 2 and at most 10 people are present in the same game room. 
- Once a game has started, no more users can join.

- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#19
- [x] #55
- [x] #48 
- [x] #114 
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#85
- [x]  sopra-fs23-group-09/SpyWithMyLittleEye_client#96
