### ISSUE TITLE
As a <user> I want to <logout> so that <my session ends>.

### ISSUE THREAD

**Issue by athzsc** [sopra-fs23-group-09/SpyWithMyLittleEye_server#90]
- User can click on a button and be logged out.
- A logged out user doesn't have access to the guarded pages anymore.

- [x] sopra-fs23-group-09/SpyWithMyLittleEye_server#91
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#140
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#237
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_client#268
- [x] sopra-fs23-group-09/SpyWithMyLittleEye_server#180
